#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
#
# Embeds compiled shader artifacts (shaders/compiled/*.msl, *.spv, built
# by tools/compile-shaders.sh) into a single C header of byte arrays.
#
# Why embed rather than load from disk at runtime: the SDL frontend is a
# relocatable single binary (and, from Task 6.1 on, an .app bundle). A
# runtime path lookup would have to guess between the build tree, the
# install prefix and the bundle's Resources/ -- three ways to fail at
# startup for zero benefit, since the artifacts are checked in and never
# change at runtime. This mirrors what the vendored ImGui SDLGPU3 backend
# does with its own shaders (imgui_impl_sdlgpu3_shaders.h).
#
# The emitted arrays hold the file bytes verbatim, with NO trailing NUL:
# SDL_GPUShaderCreateInfo.code_size is a byte count (SDL's Metal backend
# does -[NSString initWithBytes:length:]), and the ImGui backend's own
# embedded MSL blobs are likewise un-terminated.
#
# Usage: embed-shaders.py <output.h> <input> [<input> ...]

import pathlib
import sys


def c_identifier(path: pathlib.Path) -> str:
    """scene.vert.msl -> scene_vert_msl"""
    return path.name.replace(".", "_").replace("-", "_")


def main(argv: list[str]) -> int:
    if len(argv) < 3:
        print(__doc__ or "usage: embed-shaders.py <output.h> <input>...",
              file=sys.stderr)
        return 2

    out_path = pathlib.Path(argv[1])
    inputs = [pathlib.Path(p) for p in argv[2:]]

    lines = [
        "/* Generated by tools/embed-shaders.py -- DO NOT EDIT. */",
        "/* SPDX-License-Identifier: MIT */",
        "#pragma once",
        "",
    ]
    for path in inputs:
        data = path.read_bytes()
        name = c_identifier(path)
        lines.append(f"/* {path.name}: {len(data)} bytes */")
        lines.append(f"static const unsigned char {name}[] = {{")
        for i in range(0, len(data), 16):
            chunk = data[i:i + 16]
            lines.append("    " + "".join(f"0x{b:02x}," for b in chunk))
        lines.append("};")
        lines.append("")

    out_path.write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
